version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root
    ports:
      - 8000:8000
    networks:
      - lasttime-app-local

  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - "80:80"
    environment:
      BACKEND_URL: http://localhost:3000
    volumes:
      - "./frontend/src:/frontend"
    command: /start-command.sh

networks:
  lasttime-app-local:
    external: true