version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root

  api:
    depends_on:
      - dynamodb-local
    build: ./backend/
    container_name: api
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      AWS_DEFAULT_REGION: 'ap-northeast-1'
      AWS_ENDPOINT_URL: 'http://dynamodb-local:8000'
      TABLE_NAME: 'Tasks'

  frontend:
    depends_on:
      - api
    build: ./frontend/
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - "./frontend/src:/frontend"
    environment:
      BACKEND_URL:  'http://api:8080/'
    command: /bin/sh -c "envsubst '$$BACKEND_URL'< /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

