Parameters:
  BackendImageRepoName:
    Type: String
    Default: lasttime-app/backend:latest
    Description: Backend Image repository Name and Tag
  BackendServiceName:
    Type: String
    Default: lasttime-app-backend-service
    Description: Backend App Runner Service Name

Resources:
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${FrontendS3Bucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - Id: S3Origin
          DomainName: !GetAtt FrontendS3Bucket.DomainName
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_200
        DefaultCacheBehavior:
          Compress: true
          TargetOriginId: S3Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ViewerProtocolPolicy: redirect-to-https
  
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AWS::StackName

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendS3Bucket
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
