Parameters:
  BackendImageRepoName:
    Type: String
    Default: lasttime-app/backend:latest
    Description: ECR repo Name and Tag
  BackendServicename:
    Type: String
    Default: lasttime-app-backend-service-1
    Description: Name of Backend App Runner Service
  TableName:
    Type: String
    Default: lasttime-app
    Description: DynamoDB Table Name

Resources:
  BackendAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties: 
      InstanceConfiguration: 
        Cpu: 1024
        InstanceRoleArn: !GetAtt BackendInstanceRole.Arn
        Memory: 2048 
      ServiceName: !Ref BackendServicename
      SourceConfiguration: 
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageConfiguration:
            Port: 8080
            RuntimeEnvironmentVariables:
              - Name: TABLE_NAME
                Value: !Ref TableName
          ImageIdentifier: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BackendImageRepoName}'
          ImageRepositoryType: ECR

  BackendInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - tasks.apprunner.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  AppRunnerECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

Outputs:
  BackendAppRunnerServiceUrl:
    Value: !GetAtt BackendAppRunnerService.ServiceUrl
