Parameters:
  BackendImageRepoName:
    Type: String
    Default: lasttime-app/backend:latest
    Description: Backend Image repository Name and Tag
  FrontendImageRepoName:
    Type: String
    Default: lasttime-app/frontend:latest
    Description: Frontend Image repository Name and Tag
  BackendServiceName:
    Type: String
    Default: lasttime-app-backend-service
    Description: Backend App Runner Service Name
  FrontendServiceName:
    Type: String
    Default: lasttime-app-frontend-service
    Description: Frontend App Runner Service Name

Resources:
  TaskListTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  BackendAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties: 
      InstanceConfiguration: 
        Cpu: 1024
        InstanceRoleArn: !GetAtt BackendInstanceRole.Arn
        Memory: 2048 
      ServiceName: !Ref BackendServiceName
      SourceConfiguration: 
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageConfiguration:
            Port: 8080
            RuntimeEnvironmentVariables:
              - Name: TABLE_NAME
                Value: !Ref TaskListTable
          ImageIdentifier: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${BackendImageRepoName}'
          ImageRepositoryType: ECR

  FrontendAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties: 
      InstanceConfiguration: 
        Cpu: 1024
        Memory: 2048 
      ServiceName: !Ref FrontendServiceName
      SourceConfiguration: 
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageConfiguration:
            Port: 80
            RuntimeEnvironmentVariables:
              - Name: BACKEND_URL
                Value: !Sub 'https://${BackendAppRunnerService.ServiceUrl}'
            StartCommand: /start-command.sh
          ImageIdentifier: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${FrontendImageRepoName}'
          ImageRepositoryType: ECR
  
  BackendInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - tasks.apprunner.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  AppRunnerECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

Outputs:
  ServiceUrl:
    Value: !GetAtt FrontendAppRunnerService.ServiceUrl